name: Deploy React App
on: push
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test my app
        run: npm run test
      - name: Lint my app
        run: npm run lint
      - name: Build my app
        run: npm run build
      - name: Deploy
        run: echo deploying
