name: Test React App
on: push
jobs: 
  runs_non: ubuntu-latest
  steps:
    - name: Get the repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Test my app
      run: npm run test

